# Generated by Django 5.1 on 2024-09-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
