# Generated by Django 5.1 on 2024-09-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_sala_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
