# Generated by Django 5.1 on 2024-09-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_sala_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computadores',
            name='id_sala',
        ),
        migrations.RemoveField(
            model_name='perifericos',
            name='id_computador',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='id_computador',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reportes',
            name='id',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.DeleteModel(
            name='Perifericos',
        ),
        migrations.DeleteModel(
            name='Computadores',
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
        migrations.DeleteModel(
            name='Reportes',
        ),
    ]
