# Generated by Django 5.1 on 2024-09-19 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_computadores_id_sala_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PQRS',
        ),
    ]
