# Generated by Django 5.1 on 2024-09-13 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id_reportes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_reporte', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('tecnico_responsable', models.CharField(max_length=45)),
                ('id_computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.computadores')),
            ],
            options={
                'db_table': 'Reportes',
            },
        ),
    ]
