# Generated by Django 5.1 on 2024-10-02 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('room', '0002_computadores_mantenimiento_programado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='id_computador',
            field=models.ForeignKey(db_column='id_computador', on_delete=django.db.models.deletion.CASCADE, to='room.computadores' ),
        ),
    ]
