# Generated by Django 5.1 on 2024-10-04 18:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], default='Preventivo', max_length=11),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='id_computador',
            field=models.ForeignKey(db_column='id_computador', on_delete=django.db.models.deletion.CASCADE, to='room.computadores'),
        ),
    ]
