# Generated by Django 5.1 on 2024-10-04 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportes_tipo_mantenimiento_alter_reportes_fecha_and_more'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='id_computador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.computadores'),
        ),
    ]
