# Generated by Django 5.1 on 2024-08-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationtoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='token',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
