# Generated by Django 5.1 on 2024-08-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_verificationtoken_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerificationToken',
            new_name='TokenVerification',
        ),
    ]
