# Generated by Django 5.1 on 2024-09-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_alter_pqrs_estado_alter_pqrs_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqrs',
            old_name='usuario',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
    ]
