# Generated by Django 5.1 on 2024-09-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0003_rename_usuario_pqrs_id_alter_pqrs_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pqrs',
            old_name='id',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
